apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: 755548290147.dkr.ecr.us-west-2.amazonaws.com/ebs-csi-test-xiang
    newTag: latest
  - name: quay.io/k8scsi/csi-provisioner
    newTag: v1.5.0
  - name: quay.io/k8scsi/csi-attacher
    newTag: v2.2.0
  - name: quay.io/k8scsi/livenessprobe
    newTag: v2.1.0
  - name: quay.io/k8scsi/csi-node-driver-registrar
    newTag: v1.3.0
