---
# Source: aws-ebs-csi-driver/templates/csidriver.yaml
# v1 is not supported for Kubernetes version < 1.18 Update to v1beta1 if version is not compatible
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: ebs.csi.aws.com
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
spec:
  attachRequired: true
  podInfoOnMount: false
